### ISSUE TITLE
大佬，问一下SiglusTools导出的txt文本的原文如果被我改了，会影响导回的效果吗

### ISSUE THREAD

**Issue by wycstc353** [yanhua0518/GALgameScriptTools#10]
大佬，问一下SiglusTools导出的txt文本的原文如果被我改了，会影响导回的效果吗。比如我有很多对话的某个内容批量替换了，导致原文有改变，会影响导回效果吗？

**Comment by yanhua0518** [comment]
导入文本不会管原文，只要没有动行号和行号前后的标识符就不会有影响
