### ISSUE TITLE
Riodumper.py failed to dump choices

### ISSUE THREAD

**Issue by Cosetto** [yanhua0518/GALgameScriptTools#13]
There's an example code of extracting the choices [link](https://github.com/YuriSizuku/GalgameReverse/blob/cdd702c9fe21cde6b1a87dcb8886ce519231e2fd/src/advhd/advhd_wsc.py#L259-L281). And here are example scripts with choices.
[choice.zip](https://github.com/yanhua0518/GALgameScriptTools/files/11549765/choice.zip)

**Comment by yanhua0518** [comment]
Sorry
It's been so long, I‘ve no idea to update it anymore...
