### ISSUE TITLE
[REQUEST] Add the option to unpack and repack .g00 images

### ISSUE THREAD

**Issue by Darken-kun** [yanhua0518/GALgameScriptTools#14]
I don't understand much about programming, but there's this tool called [vaconv-cpp](https://drive.google.com/file/d/15VZhFmrbz32xCpAlRVKBD6ttx_iMMZAs/view?usp=sharing) that can convert g00 images to png and vice-versa.

```
USAGE:

   vaconv-cpp  [-g <int>] [-d <folder>] [--] [--version] [-h] <file> ...


Where:

   -g <int>,  --g00 <int>
     G00 format to use for output (0 or 2)

   -d <folder>,  --outdir <folder>
     Folder for output files (defaults to current directory)

   --,  --ignore_rest
     Ignores the rest of the labeled arguments following this flag.

   --version
     Displays version information and exits.

   -h,  --help
     Displays usage information and exits.

   <file>  (accepted multiple times)
     (required)  The files to convert
```

Do you think you can implement this tool in your program? Thanks in advance.

**Comment by yanhua0518** [comment]
g00 have a published official GUI tool G00packMax,
And you can use GARbro to convert g00 file much more easily.
So, add vaconv-cpp is not very useful.

Maybe I'll try it when I have time.
