### ISSUE TITLE
您好，请问DL版没有Scene.pck，应该怎么提取文本，制作汉化补丁呢？

### ISSUE THREAD

**Issue by nanfangming** [yanhua0518/GALgameScriptTools#4]
您好，请问DL版没有Scene.pck，应该怎么提取文本，制作汉化补丁呢？

**Comment by s911110** [comment]
DL版的Scene.pck封在了游戏目录下的SiglusEngine.exe里
1、如果可以的话可自行dump出来
2、如果不会，可以用siglusextract（在游戏目录下 新建记事本.txt 改为Scene.pck ，此时siglusextract正常运行，拉入Scene.pck即可解出其中的ss文件，汉化完成后，先删除目录下那个空的Scene.pck文件，然后封装刚刚解包的ss文件）

最后更改SiglusEngine.exe的名字，比如改成SiglusEngine_cn.exe使其读取目录下Scene.pck文件而非exe中的。
