### ISSUE TITLE
Request to add a license

### ISSUE THREAD

**Issue by LuqueDaniel** [yanhua0518/GALgameScriptTools#5]
Currently, no license is applied to this repository. According to https://choosealicense.com/no-permission/ it's understood by default that the user doesn't have permission to use, modify or share the code.

I would like to include part of the code from this repository in a project and I would like to know what I can and cannot do.

If you need help with this let me know!

**Comment by yanhua0518** [comment]
I'm a beginner. Don't know so much about it.
If you would like to use my code, just use it.
