### ISSUE TITLE
SiglusTools: Smart/Full Dump doesn't work with English releases?

### ISSUE THREAD

**Issue by Cerzs** [yanhua0518/GALgameScriptTools#7]
I tried with both Rewrite+ and Loopers (Trial patched), English dialogues are missing.

**Comment by yanhua0518** [comment]
The text line that only have alphabets will be dumpped in "Smart Dump" mode.
If you want to output English text, use "No dump" option in ssDumper.
(Or add -a in command line)

**Comment by Cerzs** [comment]
Thanks.
